version: '3.7'

services:
  futuru-backend:
    container_name: ${PROJECT_NAME}-backend
    build:
      context: .
      target: ${NODE_ENV}
    links:
      - "postgres:database"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:debug
    env_file:
      - .env
    depends_on:
      - postgres
    tty: true

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
